name: Failure Workflow

on:
  pull_request:
    types: [labeled, reopened, opened, synchronize, reopened]
    branches:
      - "*"

jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Clean install dependencies and build
        run: |
          sleep 10
          false
