name: Auto Merge Workflow

on:
  pull_request:
    types: [labeled, reopened]
    branches:
      - "*"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  AUTOMERGE_BRANCHES: "master,release,develop"
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create and Merge Pull Request
        uses: ./
        with:
          owner_repo: ${{ github.repository }}
