name: Auto Merge Workflow

on:
  pull_request:
    types: [labeled, reopened, opened, synchronize, reopened, assigned, ready_for_review]
    branches:
      - master
      - develop
      - release

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  DEBUG: "true"
  AUTOMERGE_BRANCHES: "master,release,develop"
jobs:
  waitForWorkflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Check if workflow is already running
        run: CHECK_IF_ALREADY_RUNNING=true node actions.js
      - name: Wait for workflows
        id: wait
        uses: ./wait-for-workflows
        with:
          max-timeout: "900"
          polling-interval: "30"
          exclude-workflow-names: "Failure Workflow"
          exclude-workflow-ids: ""
          github-token: ${{ secrets.GH_TOKEN }}
        env:
          DEBUG: "true"
  autoMerge:
    runs-on: ubuntu-latest
    needs: [waitForWorkflows]
    if: always()
    # permissions:
    #   contents: read
    #   pull-requests: write
    steps:
      - name: Check needs results
        if: needs.waitForWorkflows.result != 'success'
        run: exit 1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create and Merge Pull Request
        uses: ./
